name: Deploy to Docker App

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: docker build -t najmamoha1/my-nginx-app:latest .
      
    - name: Push Docker image to Docker Hub
      run: docker push najmamoha1/my-nginx-app:latest
      
    - name: Deploy Docker container using Docker API
      run: |
        curl -X POST \
          --unix-socket /var/run/docker.sock \
          -H "Content-Type: application/json" \
          -d '{"Image": "najmamoha1/my-nginx-app:latest", "PortBindings": { "80/tcp": [{ "HostPort": "80" }] }}' \
          http:/v1.41/containers/create
