name: Deploy to Docker App

on:
  push:
    branches:
      - master  # Adjust this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: docker build -t najmamoha1/my-nginx-app:latest .
      
    - name: Push Docker image to Docker Hub
      run: docker push najmamoha1/my-nginx-app:latest
      
    - name: SSH into your server and deploy Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull najmamoha1/my-nginx-app:latest
          docker stop my-nginx-container || true
          docker rm my-nginx-container || true
          docker run -d --name my-nginx-container -p 80:80 najmamoha1/my-nginx-app:latest
